spring:
  application:
    name: zuul-server
server:
  port: 5555
  servlet:
    context-path: /cloud
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    geek-spring-cloud-eureka-client: /gclient/**
    secured-client: /secured/**
    statistic-chain-client: /statistic/**
    secured-feign-client: /feign/**
    geek-spring-cloud-eureka-feign-client: /shop/**
  sensitiveHeaders: Cookie, Set-Cookie
#ribbon:
#  ReadTimeout: 60000